services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - app-data:/data
    

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    volumes:
      - app-data:/data

  redis:
    image: "redis:alpine"
    # ports:
    #   - "6379:6379"

volumes:
  app-data: